### PR TITLE
Add Dockerfile

### LINKED ISSUE #149: Add Dockerfile
I would be nice to have a Dockerfile so folks can run it in docker infra.

### PR DESCRIPTION
**Pull request by netflash**
I want to resolve #149 by this PR.

### CODE REVIEW

**Comment by netflash** [comment]
Any chance this gonna be merged?

**Comment by netflash** [comment]
@binaryberry ?

**Comment by binaryberry** [comment]
Thanks a lot for the contribution @netflash, with documentation to boot ! 🐳

**Comment by netflash** [comment]
You are welcome.
I love this bot, so does my team.

**Comment by binaryberry** [comment]
Lovely to hear it!

**Pull request merged**
