### PR TITLE
Update content-tools

### PR DESCRIPTION
**Pull request by chao-xian**
@leenagupte and @theleebriggs are leeving 😭. Also beefed up our daily quotes.

But @cbaines joins!

### CODE REVIEW

**Comment by chao-xian** [comment]
@leenagupte but you'll set up Seal for Scrutineers surely?

**Comment by leenagupte** [comment]
Leaving my mug should be a global charter :D

**Comment by binaryberry** [comment]
@chao-xian LGTM! Shall I wait til next Monday to merge?

**Comment by chao-xian** [comment]
@binaryberry yeah that's probably best. Just wanted to get this lined up. You can have the pleasure of hitting `Merge` for this and all the numerous other similar team updates on Monday! :squirrel:

**Pull request merged**
