### PR TITLE
Remove <> to make link display properly

### PR DESCRIPTION
**Pull request by stig**

### CODE REVIEW

**Comment by matthewford** [comment]
Don't know about everyone else but slack.com/services/new/incoming-webhook seems to work, it'll pick your last org, and you can then just switch if needed.

**Comment by stig** [comment]
Thanks! I’ve made that change. Seems good.

Stig

**Comment by johnsyweb** [comment]
:+1:

**Comment by binaryberry** [comment]
Thanks all!

**Pull request merged**
