### PR TITLE
Seal at Envato

### PR DESCRIPTION
**Pull request by johnsyweb**
Context
-----------

I :heart: this project and wish I'd written it myself! Today I got it working for Envato, in the gaps between meetings.

Changes
------------

- Get GitHub organisation from environment, rather than hard-coding it
- Correct the script names in README
- DRY-up ./bin/{angry,informative}_seal.rb by extracting a Seal class
- Implement missing `MessageBuilder#build`
- Organisation-specific configurations to prevent flipper-trampling
- Remove the requirement to list *all* members of a team (but leave valid membership checking as an option)
- @-mentions authors in Slack to get their attention
- Stopped specs hitting the Internet

Considerations
---------------------

- Get GitHub organisation from environment, rather than hard-coding it: *This will break the existing `alphagov` installation* until `SEAL_ORGANISATION` is set to `alphagov` in your Heroku instance (and your shell. I hope this is okay. I think it's for the greater good.  
- Does organisational information belong in this repository?
- Should I add this to TravisCI?

### CODE REVIEW

**Comment by binaryberry** [comment]
To the risk of repeating what i said on Twitter, thanks SO MUCH for this great pull request. 

Those are great improvements, and I'd wanted to mock Slack::Poster and Octokit for a while. 

Apart from the comment on the "@-mention authors in Slack" commit, it's ready to merge as far as I'm concerned. 

I wondered if the organisation would not be better off in the config file, but I'll probably be adding a lot of teams of my organisation in the next few months, so I'd rather not have to specify the organisation for each team each time so an ENV works out better.

Happy for you to add it to Travis CI if you'd like!

**Comment by johnsyweb** [comment]
Agreed, the @-mentions should be a configuration option. I've reverted this change and will put that in a a different PR.

Glad you like the other improvements.

Thanks for a great project!

**Comment by binaryberry** [comment]
Thanks Pete! Merged now :-)

**Comment by johnsyweb** [comment]
:bow:

**Pull request merged**
