### PR TITLE
Remove me (issyl0) from Benchmarking and add to Infrastructure

### PR DESCRIPTION
**Pull request by issyl0**
- 💔
- ❤️

### CODE REVIEW

**Comment by binaryberry** [comment]
Can I be a pain and ask you to also update benchmarking as a whole while you're there - removing markmacleod and myself and adding @Davidslv ?

**Comment by issyl0** [comment]
Sure, sorry I was selfish!

**Comment by issyl0** [comment]
Done. :-)

**Comment by binaryberry** [comment]
Merciiiii @issyl0 !

**Pull request merged**
