### PR TITLE
Travis CI for Seal

### PR DESCRIPTION
**Pull request by johnsyweb**
# Context

To give confidence when making change, we'd like to see tests passing in CI

# Changes

- Add build status badge to README
- Add travis dependencies

# Consideration

- [ ] @binaryberry needs to turn this project on at https://travis-ci.org/

### CODE REVIEW

**Comment by binaryberry** [comment]
Hi Pete, I've added my environment variables to Travis CI but don't see what (else) to do to activate it. If you have any pointers, let me know; if not, I'll ask for the help of an experienced developer in this hemisphere.

**Comment by johnsyweb** [comment]
Hi Tatiana,

You shouldn't need any environment variables for running the specs. It _should_ just be a case of going to https://travis-ci.org/profile/binaryberry and toggling binaryberry/seal (from :heavy_multiplication_x: to :heavy_check_mark: ).

I'd be happy to troubleshoot with you on [screenhero](https://screenhero.com/) or similar.

Cheers;

**Comment by binaryberry** [comment]
Thanks Pete! Got it working now with this link! I now modified the .travis.yml file to reflect the new ruby version of the seal (2.1.2), which I've upgraded to to use the Date#monday? method with Angry Seal.

**Comment by johnsyweb** [comment]
:tada: That's great, thanks!

**Pull request merged**
