### PR TITLE
Helm Chart WIP

### PR DESCRIPTION
**Pull request by netflash**
This ultimately should address #154.
not sure this is ready to merge. Expecting some feedback to improve it. /cc @bilalaslamseattle

### CODE REVIEW

**Comment by binaryberry** [comment]
Thanks @netflash for the contribution! Is there a reason why you'd like to include the helm charts with the app itself? Normally it's something that would be separate and live with the [other charts](https://github.com/kubernetes/charts/tree/master/stable).

**Comment by netflash** [comment]
@binaryberry TBH I don't have an answer. All the charts I create for personal use - I store them together with apps. Perhaps because I have never had enough time to understand how helm repository works.

**Comment by netflash** [comment]
Any advice would be highly appreciated. What should I do with this ?

**Comment by binaryberry** [comment]
Hi @netflash, sorry about the late reply! Speaking to some of my ops colleagues, it seems it's unusual adding helm charts with the app itself, and that the convention is to keep them separate. So I'm going to close this PR. Thanks for suggesting though!

**Pull request closed without merging**
