### PR TITLE
Initial bot test

### PR DESCRIPTION
**Pull request by monfresh**
- Fix auto pagination
- Ignore team members for now to fetch all org repos
- Set test channel to `#transient`
- configure exclusion of PRs based on words in their title and/or labels

### CODE REVIEW

**Comment by monfresh** [comment]
Oops. wrong repo.

**Comment by binaryberry** [comment]
:-) Hello from London Moncef! Does 18f use the seal?

**Comment by monfresh** [comment]
Hello from DC, Tatiana! We've just started playing with it, but it looks like we'll be using it. Thanks for your work on it. I'll be sending you some PRs.

**Comment by binaryberry** [comment]
Awesome news! Let me know if you need anything and i'll be happy to help :-)

**Pull request closed without merging**
